# Nimbus variant: granular mode in 8-bit mu-law mono with a 5 s buffer. See README.md.
TARGET = nimbus-lofi
NIMBUS_VARIANT = NIMBUS_VARIANT_LOFI
NIMBUS_DIR = ../nimbus
include $(NIMBUS_DIR)/nimbus.mk
